const aijaStory = () => {
  const a = (a, i) => Math.floor(Math.random() * i + a),
    i = (i) => i[a(0, i.length)],
    t = i([
      'äijät',
      'leidit',
      'frendit',
      'äijä',
      'vaimo',
      'kundi',
      'jätkät',
      'homiet',
      'homot',
      'pellet',
      'dudet',
      'jäbä',
      'spede',
      'dude',
    ]),
    s = i(['siistii', 'hyvä', 'helmee', 'äijää', 'siistii', 'asiallist', 'kuulii']),
    e = i([
      'thaikuis',
      'briteis',
      'jenkeis',
      'indois',
      'baaris',
      'balil',
      'japanis',
      'malil',
      'mäkis',
      'pohjoisnaval',
      'turkis',
      'olympialaisis',
      'ausseis',
      'brasseis',
      'meksikos',
      'kanadas',
      'gobin aavikol',
      'kapkaupungis',
      'lontoos',
      'intias',
      'asuntomessuil',
      'pakistanis',
      'etelä-naval',
      'tiibetis',
      'kiinas',
      'siperias',
      'x-gamesis',
      'ymca:s',
      'tongal',
      'tulivuores',
      'lontoos',
      'muukalaislegioonas',
      'vietnamis',
      'etelä-koreas',
      'luolas',
      'vankilassa',
      'fudiksen mm-finaalis',
      'pohjois-koreas',
      'viidakos',
      'hervannas',
      'superbowlissa',
      'hesburgeris',
      'lastentarhassa',
    ]),
    n = i([
      'surffaa',
      'skeittaa',
      'reilaa',
      'roadtripil',
      'daivaa',
      'suunnistaa',
      'kiipeilee',
      'ryyppää',
      'parkouraa',
      'seilaa',
      'wakeboardaa',
      'työharjottelus',
      'kokkaa',
      'metsästää',
      'ampumas',
      'juoksee',
      'bodaamas',
      'deejiinä',
      'ratsastaa',
      'pyöräilee',
      'töis',
      'travellaa',
      'reissaa',
      'räppää',
      'tappelemas',
      'kouluttaa',
      'suihkussa',
      'punnertaa',
      'snowboardaa',
      'maratoonis',
      'piirtää',
      'maalaan',
      'paskal',
      'kusel',
      'nyrkkeilee',
      'meditoimas',
    ]),
    u = i([
      'tänää meikä kokkaa',
      'tänää meikäijä kokkaa',
      'tänää mä väsään',
      'tänään meikä tekee',
      'tänään meitsi väsää dinneriks',
      'tänään mä duunaan',
      'pistän koht tost snadit väännöt',
    ]),
    k = i([
      'äijäwokkii',
      'viikon marinoitunutta kengurufilettä',
      'täytettyjä crepejä',
      'äijäpihvii',
      'paahdettuu lammast',
      'pakurikääpää',
      'kanttarellej',
      'virtahepoo',
      'koiraa',
      'aasinpotkaa',
      'kaviaarii',
      'miekkakalaa',
      'torvisienii',
      'jättiläismustekalaa',
      'hanhenmaksaa',
      'kobe-pihvii',
      'kateenkorvaa',
      'porsaankylkee',
      'äijäsalaattii',
      'hampurilaisii',
      'kebabbii',
      'kissaa',
      'banaaneita',
      'falafelii',
      'kanansiipii',
      'valaanlihaa',
      'kenguruu',
      'sammalta',
      'pizzaa',
      'perunoit',
      'gorillaa',
      'vyötiäistä',
      'hamstereit',
      'nokkosii',
      'apinanaivoja',
      'pässin kiveksii',
      'merihevost',
      'etanoit',
      'merimakkaraa',
      'muurahaiskarhuu',
      'haggista',
      'karitsaa',
      'käärmettä',
    ]),
    l = i([
      'wasabiemulsiol',
      'ranskalaisil',
      'pastal',
      'korianteril',
      'hummeril',
      'mädätettynä',
      'kanansiivil',
      'riisillä',
      'ruisleiväl',
      'keitettynä',
      'sushil',
      'käristettynä',
      'couscousil',
      'sokerikuorrutuksel',
      'juustol',
      'virtahevon suolessa',
      'kermaviilil',
      'yrttiöljyl',
      'maustekurkumal',
      'katkaravuil',
      'friteerattuna',
      'keittona',
      'kaviaaril',
      'höyrytettynä',
      'muurahaisilla',
      'paistettuna',
      'liekitettynä',
      'fazerin sinisellä',
      'makkaral',
      'silvottuna',
      'jugurtil',
      'vetisenä',
    ]),
    o = i([
      'tashimoto-heinää jonka poimin shiribetsu-joen rannalt kun olin reilaa japanis',
      'abessiinialaist kurttuviikunaa jota saan paikalliselt tarhurilt etiopiast',
      'mökin takapihalt poimittuu pitkälehtikihokkii',
      'sichuanin maakunnast poimittuu sareptaninsinappii',
      'tämmösii tyrnimustikka-risteytysmarjoi joita sain turun yliopiston genetiikan laitoksen äijilt',
      'perus suomalaist japaninpersiljaa jota ny löytyy kaikkien pihast',
      'neidonhiuspuu-uutet',
      'mustanmeren merilevää',
      'jauhettuu ruusunjuurta',
      'dodon höyhenii',
      'omakasvattamaa ananast',
      'jauhettuu kääpiöponinkavioo',
      'mustanmerenruusua jotka poimin georgian haikil',
      'kuopas paahdettui maakastanjoit',
      'frendin luomutilal kasvattamaa mukulakirvelii',
      'makeen kirpeit ananaskirsikoit',
      'saframii',
      'tasmanian tuholaisen karvoi',
      'basilikaa',
      'sitruunamehuu',
      'jättiläispunapuun ydintä',
      'jakinmaitorahkaa',
      'valaanrasvaa',
      'vaimon kasvattamaa minttuu',
      'jauhettuu ykssarvisen sarvee',
      'viimesen dinosauruksen suomuja',
      'murkkujen kusta',
      'koivun kaarnaa',
      'mes-juustoo pari siivuu',
    ]),
    r = i(['tuomaan', 'antaan', 'lisään']),
    m = i([
      'semmost syvyyt siihe',
      'vähä semmost itämaist twistii siihe',
      'terävyyttä tähä',
      'pehmeyttä reunoihi',
      'vähä siihe semmost twistii',
      'vähä semmost äijämäisyyt sekaa',
      'makuhermoil vähä lomafiilist',
      'vähä semmost bläästii siihe',
      'tulista twistii siihe',
    ]),
    p = () => a(1, 100) > 50,
    v = 't' === t.slice(-1);
  return `moro ${t} :D mitä ${t}. ${s} nähä ${v ? 'teit' : 'sua'} :D ${u} ${
    v ? 'teil' : 'sulle'
  } ${k} ${l}. tän reseptin opin kun olin ${e} ${n} :D pistetää sekaa vähän ${o} ${r} ${m} :D ${
    p()
      ? `dressingiks ${i([
          'vatikaanist saatuu balsamicoo, terveisii vaa konklaavin äijille :D',
          'maapähkinä-vinegrettee',
          'timjamis liuotettuu inkiväärii',
          'tämmöst viskisiirappii',
          'oliiviöljyä',
          'sivetindroppingei',
          'orpolapsien kyynelii',
          'savulohismetanaa',
          'tummaa rommii',
          'kolaa',
          'vladimirin pirtuu',
          'kossuu',
          'hp-kastiket',
          'ketsuppii',
          'poron verta',
          'meduusan limaa',
          'sinivalaan verta',
        ])}.`
      : `ja sit viel ${i([
          'pyöräytä valkokastikkees',
          'glaseerataan nopee',
          'pyöräytetää pannul limen kaa',
          'flambeerataa punkul',
          'paistetaan neljä tuntii',
          'keitetään etikassa',
          'suurustetaan',
          'kuivatetaan',
        ])} :D`
  }${
    p()
      ? ` ${i([
          'loppuun viel pikku suola',
          'lopuks viel silaus curacaoo',
          'lopuks viel pikku pippurit',
          'lopuks heitetään koko paska roskiin',
          'lopuks viel pienet öljyt',
          'lopuks viel annetaan paahtua pari tuntii',
          'lopuks viel pikku limet',
          'lopuks viel pikku chilit',
          'lopuks viel pienet pyöräytykset',
          'lopuks annetaan jäähtyy pari päivää',
          'mut alkuun pienet äijätumut',
          'mut alkuun otetaa pienet paukut',
          'lopuks annetaan hautuu pari minsaa',
        ])}.`
      : ''
  } nonii toivottavasti maistuu. mä rakastan ${v ? 'teit' : 'sua'} ${t} :D`;
};

const aijaSpurdo = () =>
  aijaStory()
    .replace(/t/g, 'd')
    .replace(/c/g, 'g')
    .replace(/k/g, 'g')
    .replace(/p/g, 'b')
    .replace(/x/g, 'gs')
    .replace(/z/g, 'ds');

module.exports = { aijaStory, aijaSpurdo };
