const dota2heroes = [
  {
    name: 'npc_dota_hero_antimage',
    id: 1,
    localized_name: 'Anti-Mage',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_axe',
    id: 2,
    localized_name: 'Axe',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_bane',
    id: 3,
    localized_name: 'Bane',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_bloodseeker',
    id: 4,
    localized_name: 'Bloodseeker',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_crystal_maiden',
    id: 5,
    localized_name: 'Crystal Maiden',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_drow_ranger',
    id: 6,
    localized_name: 'Drow Ranger',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_earthshaker',
    id: 7,
    localized_name: 'Earthshaker',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_juggernaut',
    id: 8,
    localized_name: 'Juggernaut',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_mirana',
    id: 9,
    localized_name: 'Mirana',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_nevermore',
    id: 11,
    localized_name: 'Shadow Fiend',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_morphling',
    id: 10,
    localized_name: 'Morphling',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_phantom_lancer',
    id: 12,
    localized_name: 'Phantom Lancer',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_puck',
    id: 13,
    localized_name: 'Puck',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_pudge',
    id: 14,
    localized_name: 'Pudge',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_razor',
    id: 15,
    localized_name: 'Razor',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_sand_king',
    id: 16,
    localized_name: 'Sand King',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_storm_spirit',
    id: 17,
    localized_name: 'Storm Spirit',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_sven',
    id: 18,
    localized_name: 'Sven',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_tiny',
    id: 19,
    localized_name: 'Tiny',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_vengefulspirit',
    id: 20,
    localized_name: 'Vengeful Spirit',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_windrunner',
    id: 21,
    localized_name: 'Windranger',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_zuus',
    id: 22,
    localized_name: 'Zeus',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_kunkka',
    id: 23,
    localized_name: 'Kunkka',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_lina',
    id: 25,
    localized_name: 'Lina',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_lich',
    id: 31,
    localized_name: 'Lich',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_lion',
    id: 26,
    localized_name: 'Lion',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_shadow_shaman',
    id: 27,
    localized_name: 'Shadow Shaman',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_slardar',
    id: 28,
    localized_name: 'Slardar',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_tidehunter',
    id: 29,
    localized_name: 'Tidehunter',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_witch_doctor',
    id: 30,
    localized_name: 'Witch Doctor',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_riki',
    id: 32,
    localized_name: 'Riki',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_enigma',
    id: 33,
    localized_name: 'Enigma',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_tinker',
    id: 34,
    localized_name: 'Tinker',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_sniper',
    id: 35,
    localized_name: 'Sniper',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_necrolyte',
    id: 36,
    localized_name: 'Necrophos',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_warlock',
    id: 37,
    localized_name: 'Warlock',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_beastmaster',
    id: 38,
    localized_name: 'Beastmaster',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_queenofpain',
    id: 39,
    localized_name: 'Queen of Pain',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_venomancer',
    id: 40,
    localized_name: 'Venomancer',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_faceless_void',
    id: 41,
    localized_name: 'Faceless Void',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_skeleton_king',
    id: 42,
    localized_name: 'Wraith King',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_death_prophet',
    id: 43,
    localized_name: 'Death Prophet',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_phantom_assassin',
    id: 44,
    localized_name: 'Phantom Assassin',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_pugna',
    id: 45,
    localized_name: 'Pugna',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_templar_assassin',
    id: 46,
    localized_name: 'Templar Assassin',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_viper',
    id: 47,
    localized_name: 'Viper',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_luna',
    id: 48,
    localized_name: 'Luna',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_dragon_knight',
    id: 49,
    localized_name: 'Dragon Knight',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_dazzle',
    id: 50,
    localized_name: 'Dazzle',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_rattletrap',
    id: 51,
    localized_name: 'Clockwerk',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_leshrac',
    id: 52,
    localized_name: 'Leshrac',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_furion',
    id: 53,
    localized_name: 'Nature\'s Prophet',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_life_stealer',
    id: 54,
    localized_name: 'Lifestealer',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_dark_seer',
    id: 55,
    localized_name: 'Dark Seer',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_clinkz',
    id: 56,
    localized_name: 'Clinkz',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_omniknight',
    id: 57,
    localized_name: 'Omniknight',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_enchantress',
    id: 58,
    localized_name: 'Enchantress',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_huskar',
    id: 59,
    localized_name: 'Huskar',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_night_stalker',
    id: 60,
    localized_name: 'Night Stalker',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_broodmother',
    id: 61,
    localized_name: 'Broodmother',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_bounty_hunter',
    id: 62,
    localized_name: 'Bounty Hunter',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_weaver',
    id: 63,
    localized_name: 'Weaver',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_jakiro',
    id: 64,
    localized_name: 'Jakiro',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_batrider',
    id: 65,
    localized_name: 'Batrider',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_chen',
    id: 66,
    localized_name: 'Chen',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_spectre',
    id: 67,
    localized_name: 'Spectre',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_doom_bringer',
    id: 69,
    localized_name: 'Doom',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_ancient_apparition',
    id: 68,
    localized_name: 'Ancient Apparition',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_ursa',
    id: 70,
    localized_name: 'Ursa',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_spirit_breaker',
    id: 71,
    localized_name: 'Spirit Breaker',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_gyrocopter',
    id: 72,
    localized_name: 'Gyrocopter',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_alchemist',
    id: 73,
    localized_name: 'Alchemist',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_invoker',
    id: 74,
    localized_name: 'Invoker',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_silencer',
    id: 75,
    localized_name: 'Silencer',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_obsidian_destroyer',
    id: 76,
    localized_name: 'Outworld Destroyer',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_lycan',
    id: 77,
    localized_name: 'Lycan',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_brewmaster',
    id: 78,
    localized_name: 'Brewmaster',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_shadow_demon',
    id: 79,
    localized_name: 'Shadow Demon',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_lone_druid',
    id: 80,
    localized_name: 'Lone Druid',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_chaos_knight',
    id: 81,
    localized_name: 'Chaos Knight',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_meepo',
    id: 82,
    localized_name: 'Meepo',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_treant',
    id: 83,
    localized_name: 'Treant Protector',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_ogre_magi',
    id: 84,
    localized_name: 'Ogre Magi',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_undying',
    id: 85,
    localized_name: 'Undying',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_rubick',
    id: 86,
    localized_name: 'Rubick',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_disruptor',
    id: 87,
    localized_name: 'Disruptor',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_nyx_assassin',
    id: 88,
    localized_name: 'Nyx Assassin',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_naga_siren',
    id: 89,
    localized_name: 'Naga Siren',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_keeper_of_the_light',
    id: 90,
    localized_name: 'Keeper of the Light',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_wisp',
    id: 91,
    localized_name: 'Io',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_visage',
    id: 92,
    localized_name: 'Visage',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_slark',
    id: 93,
    localized_name: 'Slark',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_medusa',
    id: 94,
    localized_name: 'Medusa',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_troll_warlord',
    id: 95,
    localized_name: 'Troll Warlord',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_centaur',
    id: 96,
    localized_name: 'Centaur Warrunner',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_magnataur',
    id: 97,
    localized_name: 'Magnus',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_shredder',
    id: 98,
    localized_name: 'Timbersaw',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_bristleback',
    id: 99,
    localized_name: 'Bristleback',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_tusk',
    id: 100,
    localized_name: 'Tusk',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_skywrath_mage',
    id: 101,
    localized_name: 'Skywrath Mage',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_abaddon',
    id: 102,
    localized_name: 'Abaddon',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_elder_titan',
    id: 103,
    localized_name: 'Elder Titan',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_legion_commander',
    id: 104,
    localized_name: 'Legion Commander',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_ember_spirit',
    id: 106,
    localized_name: 'Ember Spirit',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_earth_spirit',
    id: 107,
    localized_name: 'Earth Spirit',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_terrorblade',
    id: 109,
    localized_name: 'Terrorblade',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_phoenix',
    id: 110,
    localized_name: 'Phoenix',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_oracle',
    id: 111,
    localized_name: 'Oracle',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_techies',
    id: 105,
    localized_name: 'Techies',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_winter_wyvern',
    id: 112,
    localized_name: 'Winter Wyvern',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_arc_warden',
    id: 113,
    localized_name: 'Arc Warden',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_abyssal_underlord',
    id: 108,
    localized_name: 'Underlord',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_monkey_king',
    id: 114,
    localized_name: 'Monkey King',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_pangolier',
    id: 120,
    localized_name: 'Pangolier',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_dark_willow',
    id: 119,
    localized_name: 'Dark Willow',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_grimstroke',
    id: 121,
    localized_name: 'Grimstroke',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_mars',
    id: 129,
    localized_name: 'Mars',
    type: 'strength',
  },
  {
    name: 'npc_dota_hero_void_spirit',
    id: 126,
    localized_name: 'Void Spirit',
    type: 'agility',
  },
  {
    name: 'npc_dota_hero_snapfire',
    id: 128,
    localized_name: 'Snapfire',
    type: 'mana',
  },
  {
    name: 'npc_dota_hero_hoodwink',
    id: 123,
    localized_name: 'Hoodwink',
    type: 'agility',
  },
];

module.exports = dota2heroes;
